---
AWSTemplateFormatVersion: 2010-09-09

Parameters:

  TableName:
    Type: String


Resources:

  UserTable:
    Type: AWS::DynamoDB::Table
    Description: Holds users info.
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: "userId"
          AttributeType: "S"
        - AttributeName: "dateAdded"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "userId"
          KeyType: "HASH"
        - AttributeName: "dateAdded"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: Purpose
          Value: User Info Table
